// This macro is to be run using `root -q -b normalizeParallelJobs.C+`
// It's purpose is to normalize the histograms generated by L1EGRateStudies.cc
// if they were produced in parallel (e.g. with Condor)
// 
// rootools can be found in ~nsmith/src/rootools
// It's just a small collection of useful utilities
#include "rootools.h"

#include <memory>
#include <iostream>
#include "TH1F.h"
#include "TGraphAsymmErrors.h"
#include "TObject.h"
#include "TDirectory.h"


void normalizeParallelJobs() {

    TFile * eff = new TFile("egTriggerEff.root", "UPDATE");
    TFile * rates = new TFile("egTriggerRates.root", "UPDATE");

    // We need to renormalize everything since these files were parallel processed
 
    auto effHistKeys = rootools::getKeysofClass(eff, "analyzer", "TH1F");
    auto effPtDenom = (TH1F *) eff->Get("analyzer/gen_pt");
    auto effEtaDenom = (TH1F *) eff->Get("analyzer/gen_eta");
    if ( effPtDenom != nullptr )
    {
        std::cout << "Dividing efficiency histograms by gen hists" << std::endl;
        std::cout << "Total event count: " << effPtDenom->Integral() << std::endl;
        
        eff->cd("analyzer");
        auto effPtHists = rootools::loadObjectsMatchingPattern<TH1F>(effHistKeys, "*_efficiency*pt");
        for(auto& hist : effPtHists) 
        {
            auto graph = new TGraphAsymmErrors(hist, effPtDenom);
            graph->GetXaxis()->SetTitle(hist->GetXaxis()->GetTitle());
            graph->GetYaxis()->SetTitle("Efficiency");
            graph->Write();
        }
        auto effEtaHists = rootools::loadObjectsMatchingPattern<TH1F>(effHistKeys, "*_efficiency*eta");
        effEtaDenom->Sumw2();
        for(auto& hist : effEtaHists)
        {
            auto graph = new TGraphAsymmErrors(hist, effEtaDenom);
            graph->GetXaxis()->SetTitle(hist->GetXaxis()->GetTitle());
            graph->GetYaxis()->SetTitle("Efficiency");
            graph->Write();
        }
        auto dir = (TDirectory*) eff->Get("analyzer");
        dir->Delete("gen_pt;*");
        dir->Delete("gen_eta;*");
        eff->Write("", TObject::kOverwrite);
    }

    auto rateHistKeys = rootools::getKeysofClass(rates, "analyzer", "TH1F");
    if ( rates->Get("analyzer/eventCount") != nullptr )
    {
        std::cout << "Normalizing rate histograms to 30MHz" << std::endl;
        int nEvents = ((TH1F*)rates->Get("analyzer/eventCount"))->GetBinContent(1);
        std::cout << "Total event count: " << nEvents << std::endl;
        auto rateHists = rootools::loadObjectsMatchingPattern<TH1F>(rateHistKeys, "*_rate*");
        for(auto& hist : rateHists)
        {
            hist->Sumw2();
            hist->Scale(30000./nEvents);
        }
        auto dir = (TDirectory*) rates->Get("analyzer");
        dir->Delete("eventCount;*");
        rates->Write("", TObject::kOverwrite);
    }
}
